Repository auth0/Auth0.swift, pull requests merged in 2019-07, with the labels that each got.

#286 Fix: Remove force unwrap in AuthSession handler
  Auth0/SafariAuthenticationSession.swift
  Auth0/WebAuthError.swift
Labels: CH: Fixed

#281 Fix Dismiss AS/SF authentication sessions upon deep-link callback
  Auth0/SafariAuthenticationSession.swift
Labels: CH: Fixed, medium

#287 Added support for root attributes when creating a new user
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/SafariWebAuth.swift
  Auth0Tests/AuthenticationSpec.swift
Labels: CH: Added

#289 Fixed ObjMembers attribute added for ObjC access
  Auth0/Profile.swift
  Auth0/SafariAuthenticationSession.swift
  Auth0/UserInfo.swift
  Gemfile
  Gemfile.lock
Labels: CH: Fixed, small
