Repository auth0/Auth0.swift, pull requests merged in 2019-10, with the labels that each got.

#312 CredentialsManager function to clear and revoke the refresh token
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0Tests/CredentialsManagerSpec.swift
  README.md
Labels: CH: Added, medium

#318 Fix non-main thread use during inspection in SafariViewController [SDK-1119]
  Auth0/SafariWebAuth.swift
Labels: CH: Fixed

#319 Renew tokens in Credentials Manager if either token has expired [SDK-999]
  Auth0/CredentialsManager.swift
  Auth0/OAuth2Grant.swift
  Auth0/SafariWebAuth.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Cartfile.resolved
Labels: CH: Added, small
