Repository auth0/Auth0.swift, pull requests merged in 2020-01, with the labels that each got.

#330 Implement passwordless login [SDK-1185]
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
Labels: CH: Added, P1: Urgent, medium

#336 Added missing watchOS shared scheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.watchOS.xcscheme
Labels: CH: Fixed, tiny

#337 Improve OIDC compliance: add signature validation support
  Auth0.xcodeproj/project.pbxproj
  Auth0/ClaimsValidators.swift
  Auth0/CredentialsManager.swift
  Auth0/IDTokenSignatureValidator.swift
  Auth0/IDTokenValidator.swift
  Auth0/IDTokenValidatorContext.swift
  Auth0/JWT+Header.swift
  Auth0/OAuth2Grant.swift
  Auth0/Optional+DebugDescription.swift
  Auth0Tests/Generators.swift
  Auth0Tests/IDTokenSignatureValidatorSpec.swift
  Auth0Tests/IDTokenValidatorBaseSpec.swift
  Auth0Tests/IDTokenValidatorMocks.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/JWKSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/Responses.swift
Labels: CH: Added, enhancement, large

#338 Added a Table of Contents to the README
  README.md
Labels: CH: Changed, documentation, small

#342 Exposing additional swift calls to objective c
  Auth0/_ObjectiveAuthenticationAPI.swift
Labels: CH: Added, P4: Nice to Have, small

#340 Improve OIDC compliance: add claims validation
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/ClaimValidators.swift
  Auth0/ClaimsValidators.swift
  Auth0/IDTokenSignatureValidator.swift
  Auth0/IDTokenValidator.swift
  Auth0/IDTokenValidatorContext.swift
  Auth0/JWKS.swift
  Auth0/JWTAlgorithm.swift
  Auth0Tests/ClaimValidatorsSpec.swift
  Auth0Tests/Generators.swift
  Auth0Tests/IDTokenValidatorBaseSpec.swift
  Auth0Tests/IDTokenValidatorMocks.swift
  Auth0Tests/IDTokenValidatorSpec.swift
Labels: CH: Added, large

#344 Improve OIDC compliance: integrate IDTV
  Auth0/CredentialsManager.swift
  Auth0/IDTokenValidator.swift
  Auth0/IDTokenValidatorContext.swift
  Auth0/OAuth2Grant.swift
  Auth0/SafariWebAuth.swift
  Auth0/WebAuth.swift
  Auth0/WebAuthError.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/BioAuthenticationSpec.swift
  Auth0Tests/CredentialsSpec.swift
  Auth0Tests/IDTokenValidatorBaseSpec.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/NativeAuthSpec.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Auth0Tests/SafariSessionSpec.swift
  Auth0Tests/WebAuthSpec.swift
Labels: CH: Changed, large

#345 Execute the ID Token validation on a worker thread
  Auth0/IDTokenValidator.swift
  Auth0Tests/IDTokenValidatorMocks.swift
  Auth0Tests/IDTokenValidatorSpec.swift
Labels: CH: Changed, medium
