Repository auth0/Auth0.swift, pull requests merged in 2020-08, with the labels that each got.

#408 Added isVerificationRequired error [SDK-1865]
  Auth0/AuthenticationError.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  README.md
Labels: CH: Added, small

#409 Added CredentialsManager to watchOS target [SDK-1906]
  Auth0.podspec
  Auth0.xcodeproj/project.pbxproj
Labels: CH: Added, tiny

#410 Use 'connection' parameter for webauth
  README.md
Labels: tiny

#414 Added issue templates [SDK-1852]
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
Labels: CH: Added, documentation, small
