Repository auth0/Auth0.swift, pull requests merged in 2020-03, with the labels that each got.

#358 Added Facebook token exchange method [SDK-1401]
  Auth0/Auth0Authentication.swift
  Auth0/AuthTransaction.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
Labels: CH: Added, medium

#361 Updated Facebook subject_token_type
  Auth0/Auth0Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
Labels: CH: Fixed, tiny

#360 [Snyk] Fix for 3 vulnerabilities
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: tiny

#364 Update README.md
  README.md
Labels: small

#365 Added support for iOS extensions
  Auth0.podspec
  Auth0.xcodeproj/project.pbxproj
  Auth0/ControllerModalPresenter.swift
  Auth0/SafariAuthenticationCallback.swift
  Auth0/SafariAuthenticationSession.swift
  Auth0/UIApplication+Shared.swift
Labels: CH: Added, small

#366 Added updated Gemfile.lock
  Gemfile.lock
Labels: tiny

#369 Added support for Refresh Token Rotation [SDK-1420]
  Auth0/Authentication.swift
  Auth0/CredentialsManager.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/Responses.swift
Labels: CH: Added, small

#370 Renamed native social login methods
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
  README.md
Labels: CH: Deprecated, medium

#371 Release 1.23.0
  App/Info.plist
  Auth0/Info-tvOS.plist
  Auth0/Info.plist
  Auth0Tests/Info.plist
  CHANGELOG.md
  OAuth2Mac/Info.plist
  OAuth2TV/Info.plist
Labels: small
