Repository auth0/Auth0.swift, pull requests merged in 2021-11, with the labels that each got.

#528 Add Migration guide template
  V2_MIGRATION_GUIDE.md
Labels: review:tiny

#530 Remove `parameters` from Authentication API client methods [SDK-2902]
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/_ObjectiveAuthenticationAPI.swift
  Auth0Tests/AuthenticationSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#534 Update the migration guide for SDK-2896, SDK-2897 and 2900
  V2_MIGRATION_GUIDE.md
Labels: documentation, review:tiny

#531 Drop support for Swift < 5.3 [SDK-2896]
  App/AppDelegate.swift
  Auth0.podspec
  Auth0/ASCallbackTransaction.swift
  Auth0/ASTransaction.swift
  Auth0/Auth0WebAuth.swift
  Auth0/DesktopWebAuth.swift
  Auth0/MobileWebAuth.swift
  Auth0/Profile.swift
  Auth0/Telemetry.swift
  Auth0/WebAuth.swift
  Auth0Tests/WebAuthSpec.swift
  OAuth2TV/AppDelegate.swift
  Package.swift
  README.md
Labels: review:tiny

#532 Drop support for HS256 [SDK-2897]
  Auth0/JWTAlgorithm.swift
  Auth0Tests/CryptoExtensions.swift
  Auth0Tests/IDTokenSignatureValidatorSpec.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/JWKSpec.swift
  Auth0Tests/JWTAlgorithmSpec.swift
Labels: review:tiny

#533 Make some `Credentials` properties non-optional [SDK-2900]
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/IDTokenValidator.swift
  Auth0/OAuth2Grant.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/CredentialsSpec.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/OAuth2GrantSpec.swift
Labels: review:small

#535 Enforce `openid` scope on Web Auth [SDK-2924]
  Auth0/Auth0WebAuth.swift
  Auth0Tests/WebAuthSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#540 Use `openid profile email` as the default scope value [SDK-2926]
  Auth0/Auth0.swift
  Auth0/Auth0Authentication.swift
  Auth0/Auth0WebAuth.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/WebAuthSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#543 Remove deprecated methods [SDK-2893]
  App/AppDelegate.swift
  Auth0.podspec
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0Authentication.swift
  Auth0/Auth0WebAuth.swift
  Auth0/AuthProvider.swift
  Auth0/Authentication.swift
  Auth0/CredentialsManager.swift
  Auth0/DesktopWebAuth.swift
  Auth0/Identity.swift
  Auth0/MobileWebAuth.swift
  Auth0/NSApplication+Shared.swift
  Auth0/NativeAuth.swift
  Auth0/Profile.swift
  Auth0/Request.swift
  Auth0/UIApplication+Shared.swift
  Auth0/UserInfo.swift
  Auth0/WebAuth.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/IdentitySpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/NativeAuthSpec.swift
  Auth0Tests/ProfileSpec.swift
  Auth0Tests/WebAuthSpec.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#548 Make credentials renewal thread-safe [SDK-2903]
  Auth0/CredentialsManager.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/Responses.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:medium

#549 Replace `JSONObjectPayload` with `Codable` on `Credentials` [SDK-2958]
  Auth0/Auth0Authentication.swift
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/Telemetry.swift
  Auth0Tests/Auth0Spec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/CredentialsSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:medium

#547 Migrate existing Objective-C code to Swift [SDK-2905]
  Auth0.podspec
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0.h
  Auth0/ChallengeGenerator.swift
  Auth0/JWTAlgorithm.swift
  Auth0/OAuth2Grant.swift
  Auth0/ObjectiveC/A0ChallengeGenerator.h
  Auth0/ObjectiveC/A0ChallengeGenerator.m
  Auth0/ObjectiveC/A0RSA.h
  Auth0/ObjectiveC/A0RSA.m
  Auth0/ObjectiveC/A0SHA.h
  Auth0/ObjectiveC/A0SHA.m
  Auth0Tests/BaseTransactionSpec.swift
  Auth0Tests/ChallengeGeneratorSpec.swift
  Auth0Tests/CryptoExtensions.swift
  Auth0Tests/Generators.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Package.swift
Labels: review:large

#551 Decouple Credentials Manager storage from SimpleKeychain [SDK-2936]
  Auth0/CredentialsManager.swift
  Auth0Tests/CredentialsManagerSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#552 Migrate all errors to structs [SDK-2968]
  Auth0/ASTransaction.swift
  Auth0/Array+Encode.swift
  Auth0/Auth0Error.swift
  Auth0/Auth0WebAuth.swift
  Auth0/AuthenticationError.swift
  Auth0/BaseTransaction.swift
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0/Handlers.swift
  Auth0/JWK+RSA.swift
  Auth0/Management.swift
  Auth0/ManagementError.swift
  Auth0/OAuth2Grant.swift
  Auth0/Request.swift
  Auth0/Response.swift
  Auth0/WebAuthError.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/WebAuthErrorSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:large

#553 Update CI config
  .circleci/config.yml
Labels: review:tiny

#554 Update Codecov config
  codecov.yml
Labels: review:tiny

#555 Remove leftover files
  Auth0.xcodeproj/project.pbxproj
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.iOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.macOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.tvOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.watchOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/OAuth2.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/OAuth2Mac.xcscheme
  Auth0/Info-tvOS.plist
  Auth0/ObjectiveC/include/headers.h
  Auth0Tests/Auth0Tests.OSX-Bridging-Header.h
  Auth0Tests/Auth0Tests.iOS-Bridging-Header.h
Labels: review:small

#556 Add support for custom URL sessions to Web Auth [SDK-2906]
  Auth0/Auth0.swift
  Auth0/Auth0WebAuth.swift
  Auth0/AuthenticationError.swift
  Auth0/JWK+RSA.swift
  Auth0/ManagementError.swift
  Auth0/OAuth2Grant.swift
  Auth0/WebAuth.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/ManagementSpec.swift
  Auth0Tests/WebAuthSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#557 Add support for subpaths in Auth0 domain [SDK-2963]
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0.swift
  Auth0/Auth0Authentication.swift
  Auth0/Auth0WebAuth.swift
  Auth0/NSURL+Auth0.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
  Auth0Tests/Auth0Spec.swift
  Auth0Tests/ClaimValidatorsSpec.swift
  Auth0Tests/IDTokenValidatorBaseSpec.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Auth0Tests/WebAuthSpec.swift
  OAuth2Mac/OAuth2Mac.entitlements
  V2_MIGRATION_GUIDE.md
Labels: medium
