Repository auth0/Auth0.swift, pull requests merged in 2021-12, with the labels that each got.

#558 Use strictly-typed result and error types [SDK-2977]
  App/ViewController.swift
  Auth0/ASTransaction.swift
  Auth0/Auth0.swift
  Auth0/Auth0Error.swift
  Auth0/Auth0WebAuth.swift
  Auth0/AuthenticationError.swift
  Auth0/BaseTransaction.swift
  Auth0/CredentialsManager.swift
  Auth0/Handlers.swift
  Auth0/Management.swift
  Auth0/ManagementError.swift
  Auth0/OAuth2Grant.swift
  Auth0/Request.swift
  Auth0/Requestable.swift
  Auth0/Response.swift
  Auth0/WebAuth.swift
  Auth0/WebAuthError.swift
  Auth0Tests/BaseTransactionSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/ManagementSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/WebAuthSpec.swift
  Package.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:large

#559 Add tests for global functions
  Auth0/Auth0.swift
  Auth0/WebAuth.swift
  Auth0Tests/Auth0Spec.swift
Labels: review:medium

#560 Remove Web Auth method embedded in Authentication API client
  Auth0/Auth0WebAuth.swift
  Auth0/Authentication.swift
  Auth0/CredentialsManager.swift
  Auth0Tests/AuthenticationSpec.swift
  Package.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#563 Fix tests that were reaching the network
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Cartfile.resolved
Labels: review:small

#562 Add a way to pass custom headers directly to the request [SDK-2908]
  Auth0.xcodeproj/project.pbxproj
  Auth0/CredentialsManager.swift
  Auth0/Request.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/RequestSpec.swift
Labels: review:medium

#565 Do not use the message from the underlying error
  Auth0/CredentialsManagerError.swift
  Auth0/WebAuthError.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  Auth0Tests/WebAuthErrorSpec.swift
Labels: review:small

#564 Update Podspec
  Auth0.podspec
Labels: review:small

#566 Add support for Combine [SDK-2907]
  Auth0/Auth0Authentication.swift
  Auth0/Auth0WebAuth.swift
  Auth0/CredentialsManager.swift
  Auth0/Request.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
  Auth0Tests/Auth0Spec.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/BioAuthenticationSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/JWKSpec.swift
  Auth0Tests/RequestSpec.swift
  README.md
Labels: review:large

#567 Move access modifiers from extension methods to extension declarations
  Auth0/Auth0WebAuth.swift
  Auth0/AuthenticationError.swift
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0/ManagementError.swift
  Auth0/Request.swift
  Auth0/Telemetry.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
  Auth0/WebAuthError.swift
  Auth0Tests/WebAuthSpec.swift
Labels: review:small

#568 Use memberwise initializers in elegible structs
  Auth0/IDTokenValidatorContext.swift
  Auth0/UserInfo.swift
Labels: review:tiny

#569 Use `Auth0Error` for ID Token validation errors
  Auth0/Auth0Error.swift
  Auth0/AuthenticationError.swift
  Auth0/ClaimValidators.swift
  Auth0/CredentialsManagerError.swift
  Auth0/IDTokenSignatureValidator.swift
  Auth0/IDTokenValidator.swift
  Auth0/JWTAlgorithm.swift
  Auth0/ManagementError.swift
  Auth0/WebAuthError.swift
  Auth0Tests/ClaimValidatorsSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/IDTokenSignatureValidatorSpec.swift
  Auth0Tests/IDTokenValidatorMocks.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/JWTAlgorithmSpec.swift
  Auth0Tests/RequestSpec.swift
  Auth0Tests/WebAuthErrorSpec.swift
Labels: review:medium

#570 Make `AuthTransaction` protocol internal
  Auth0/AuthTransaction.swift
  V2_MIGRATION_GUIDE.md
Labels: review:tiny

#571 Add custom description to `Credentials`
  Auth0/Credentials.swift
  Auth0Tests/CredentialsSpec.swift
Labels: review:small

#572 Add support for async/await [SDK-2981]
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0WebAuth.swift
  Auth0/CredentialsManager.swift
  Auth0/CredentialsStorage.swift
  Auth0/NSURLComponents+OAuth2.swift
  Auth0/OAuth2Grant.swift
  Auth0/Request.swift
  Auth0/WebAuth.swift
  Auth0Tests/BaseTransactionSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Auth0Tests/RequestSpec.swift
  Auth0Tests/UsersSpec.swift
  Package.swift
  README.md
Labels: review:large

#573 Remove parameterless `tokenExchange()` method
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/OAuth2Grant.swift
  Auth0Tests/AuthenticationSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#574 Do not check for Refresh Token presence in `hasValid(minTTL:)`
  Auth0/CredentialsManager.swift
  Auth0Tests/CredentialsManagerSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#576 Add missing tests for error types
  Auth0.xcodeproj/project.pbxproj
  Auth0/Auth0Error.swift
  Auth0/AuthenticationError.swift
  Auth0/ManagementError.swift
  Auth0/Response.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/BaseTransactionSpec.swift
  Auth0Tests/CredentialsManagerErrorSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/IDTokenSignatureValidatorSpec.swift
  Auth0Tests/ManagementErrorSpec.swift
  Auth0Tests/ManagementSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Auth0Tests/UsersSpec.swift
  Auth0Tests/WebAuthErrorSpec.swift
  Auth0Tests/WebAuthSpec.swift
  README.md
Labels: review:large

#577 Update all code documentation [SDK-2983]
  Auth0/Array+Encode.swift
  Auth0/Auth0.swift
  Auth0/Auth0Error.swift
  Auth0/AuthTransaction.swift
  Auth0/Authentication.swift
  Auth0/AuthenticationError.swift
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0/CredentialsStorage.swift
  Auth0/JWK+RSA.swift
  Auth0/JWKS.swift
  Auth0/JWT+Header.swift
  Auth0/Loggable.swift
  Auth0/Management.swift
  Auth0/ManagementError.swift
  Auth0/NSData+URLSafe.swift
  Auth0/Optional+DebugDescription.swift
  Auth0/Request.swift
  Auth0/String+URLSafe.swift
  Auth0/Telemetry.swift
  Auth0/TransactionStore.swift
  Auth0/UserInfo.swift
  Auth0/UserPatchAttributes.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
  Auth0/WebAuthError.swift
  README.md
Labels: review:large

#578 Add missing test cases
  Auth0/Auth0.swift
  Auth0/Auth0Authentication.swift
  Auth0/Auth0WebAuth.swift
  Auth0/Logger.swift
  Auth0/NSData+URLSafe.swift
  Auth0/Response.swift
  Auth0/Telemetry.swift
  Auth0Tests/Auth0Spec.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  Auth0Tests/AuthenticationSpec.swift
  Auth0Tests/BaseTransactionSpec.swift
  Auth0Tests/BioAuthenticationSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  Auth0Tests/CredentialsSpec.swift
  Auth0Tests/IDTokenSignatureValidatorSpec.swift
  Auth0Tests/IDTokenValidatorSpec.swift
  Auth0Tests/LoggerSpec.swift
  Auth0Tests/ManagementErrorSpec.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/OAuth2GrantSpec.swift
  Auth0Tests/RequestSpec.swift
  Auth0Tests/ResponseSpec.swift
  Auth0Tests/Responses.swift
  Auth0Tests/TelemetrySpec.swift
  Auth0Tests/UserInfoSpec.swift
  Auth0Tests/UsersSpec.swift
  Auth0Tests/WebAuthSpec.swift
Labels: review:large

#579 Expand code documentation snippets
  Auth0/Auth0.swift
  Auth0/Authentication.swift
  Auth0/AuthenticationError.swift
  Auth0/Credentials.swift
  Auth0/Loggable.swift
  Auth0/Management.swift
  Auth0/Request.swift
  Auth0/Response.swift
  Auth0/Telemetry.swift
  Auth0/UserPatchAttributes.swift
  Auth0/Users.swift
  README.md
Labels: review:large

#581 Re-add `info` to `AuthenticationError` and `ManagementError`
  Auth0/Auth0Error.swift
  Auth0/AuthenticationError.swift
  Auth0/ManagementError.swift
  Auth0Tests/AuthenticationErrorSpec.swift
  Auth0Tests/ManagementErrorSpec.swift
  Auth0Tests/Matchers.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#582 Have the `revoke()` method of the Credentials Manager yield a `Result`
  Auth0/CredentialsManager.swift
  Auth0Tests/CredentialsManagerSpec.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#583 Add wrappers with default values for MFA methods
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
Labels: review:small

#584 Have `clearSession()` yield a `Result<Void, WebAuthError>`
  App/ViewController.swift
  Auth0.xcodeproj/project.pbxproj
  Auth0/ASCallbackTransaction.swift
  Auth0/Auth0WebAuth.swift
  Auth0/BaseCallbackTransaction.swift
  Auth0/WebAuth.swift
  Auth0Tests/Matchers.swift
  Auth0Tests/WebAuthSpec.swift
  OAuth2Mac/ViewController.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#585 Update the Migration guide [SDK-2980]
  V2_MIGRATION_GUIDE.md
Labels: review:small

#586 Improve the migration guide
  V2_MIGRATION_GUIDE.md
Labels: review:large

#588 Add a FAQ [SDK-3015]
  FAQ.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#591 Update SwiftLint configuration
  .swiftlint.yml
  Auth0/Authentication.swift
  Auth0/UserInfo.swift
  Auth0/WebAuth.swift
Labels: review:tiny

#590 Update README [SDK-2914]
  FAQ.md
  README.md
Labels: review:large

#594 Add support policy for Xcode, Swift and platform versions [SDK-2922]
  FAQ.md
  README.md
  V2_MIGRATION_GUIDE.md
  sso-alert.png
Labels: review:small

#595 Fix flaky tests in CredentialsManagerSpec
  Auth0Tests/CredentialsManagerSpec.swift
Labels: review:small

#596 Rename `refreshFailed` to `renewFailed`
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0Tests/CredentialsManagerErrorSpec.swift
  Auth0Tests/CredentialsManagerSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#597 Rename `createUser` to `signup`
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/WebAuth.swift
  Auth0Tests/AuthenticationSpec.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#598 Update the issue and PR templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: review:small

#599 Add more documentation to the README
  README.md
Labels: review:medium

#600 Rename `rsaModulus` and `rsaExponent`
  Auth0/JWK+RSA.swift
  Auth0/JWKS.swift
  Auth0Tests/Generators.swift
  Auth0Tests/JWKSpec.swift
  Auth0Tests/Responses.swift
Labels: review:small

#601 Make the `Challenge.CodingKeys` enum internal
  Auth0/Challenge.swift
  V2_MIGRATION_GUIDE.md
Labels: review:tiny

#602 Rename `realm` parameter to `realmOrConnection`
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#603 Use more descriptive `CredentialsManagerError` messages
  Auth0/CredentialsManagerError.swift
  Auth0Tests/CredentialsManagerErrorSpec.swift
Labels: review:small

#604 Use more descriptive `WebAuthError` messages
  Auth0/Auth0WebAuth.swift
  Auth0/WebAuthError.swift
  Auth0Tests/WebAuthErrorSpec.swift
  Auth0Tests/WebAuthSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#605 Move `PasswordlessType` to its own file
  Auth0.xcodeproj/project.pbxproj
  Auth0/Authentication.swift
  Auth0/PasswordlessType.swift
Labels: review:small

#606 Improve code documentation
  .github/ISSUE_TEMPLATE/report-a-bug.md
  Auth0/Auth0.swift
  Auth0/Auth0Authentication.swift
  Auth0/Auth0Error.swift
  Auth0/AuthTransaction.swift
  Auth0/Authentication.swift
  Auth0/AuthenticationError.swift
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/CredentialsManagerError.swift
  Auth0/ManagementError.swift
  Auth0/Request.swift
  Auth0/Telemetry.swift
  Auth0/TransactionStore.swift
  Auth0/UserInfo.swift
  Auth0/UserPatchAttributes.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
  Auth0/WebAuthError.swift
  README.md
Labels: review:medium

#608 Align the README with the new Quickstart
  README.md
Labels: review:small

#607 Remove remaining `parameters` parameter
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0Tests/AuthenticationSpec.swift
  V2_MIGRATION_GUIDE.md
Labels: review:small

#611 Make `UserPatchAttributes` class final
  Auth0/UserPatchAttributes.swift
  V2_MIGRATION_GUIDE.md
Labels: review:tiny

#613 Remove local parameter names from passwordless login methods
  Auth0/Auth0Authentication.swift
  Auth0/Authentication.swift
  Auth0/CredentialsManagerError.swift
  Auth0/Users.swift
  Auth0/WebAuth.swift
Labels: review:small

#612 Add more documentation to the README
  FAQ.md
  README.md
Labels: review:small
