Repository auth0/Auth0.swift, pull requests merged in 2022-06, with the labels that each got.

#702 Update `SFSafariViewController` information in FAQ
  FAQ.md
Labels: documentation, review:tiny

#703 Update the library description in the README
  README.md
Labels: documentation, review:tiny

#705 Apply recommended Xcode 14 settings
  Auth0.xcodeproj/project.pbxproj
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.iOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.macOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.tvOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/Auth0.watchOS.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/OAuth2.xcscheme
  Auth0.xcodeproj/xcshareddata/xcschemes/OAuth2Mac.xcscheme
Labels: review:small

#706 Pin SimpleKeychain to v0.x
  Auth0.podspec
  Cartfile
  Cartfile.resolved
Labels: review:tiny

#708 Update README.md
  README.md
Labels: review:tiny
