Repository auth0/Auth0.swift, pull requests merged in 2022-03, with the labels that each got.

#662 Add more API documentation for `useEphemeralSession()`
  Auth0/WebAuth.swift
Labels: review:tiny

#661 Add sectional tables of content
  README.md
Labels: review:small

#663 [SDK-3093] Remove Beta labelling from README
  README.md
Labels: review:tiny

#666 Tweak the general Table of Contents
  README.md
Labels: review:tiny

#669 Update ToC of Migration Guide
  V2_MIGRATION_GUIDE.md
Labels: documentation

#670 Update instructions in the README
  README.md
Labels: documentation, review:tiny

#671 Update gems
  Gemfile.lock
Labels: review:tiny
