Repository auth0/Auth0.swift, pull requests merged in 2023-12, with the labels that each got.

#808 docs: Update Platforms Support Policy in README
  README.md
Labels: documentation, review:tiny

#809 Add DoCC article on Web Auth user agents
  Auth0.xcodeproj/project.pbxproj
  Documentation.docc/Documentation.md
  Documentation.docc/WebAuth/UserAgents.md
Labels: documentation, review:small

#814 Fix SwiftLint warnings
  Auth0/IDTokenSignatureValidator.swift
  Auth0/OAuth2Grant.swift
Labels: review:tiny

#812 Use the new syntax for Markdown admonitions
  CONTRIBUTING.md
  EXAMPLES.md
  FAQ.md
  README.md
  V2_MIGRATION_GUIDE.md
Labels: review:small

#813 Use Xcode 15 on CI
  .github/workflows/main.yml
Labels: review:tiny

#815 Deprecate methods related to updating user attributes using the Management API
  Auth0/UserPatchAttributes.swift
  Auth0/Users.swift
Labels: review:tiny

#816 Update API docs
  Auth0/Auth0.swift
  Auth0/Credentials.swift
  Auth0/CredentialsManager.swift
  Auth0/SafariProvider.swift
  Auth0/WebAuth.swift
  Documentation.docc/WebAuth/UserAgents.md
  EXAMPLES.md
Labels: documentation, review:small
